package com.github.pires.obd.reader

import android.content.Context
import android.os.Environment
import android.util.Log
import com.github.pires.obd.commands.ObdCommand
import com.github.pires.obd.enums.AvailableCommandNames
import com.sergiojosemp.obddashboard.model.PreferencesHelper
import java.io.BufferedWriter
import java.io.File
import java.io.FileNotFoundException
import java.io.FileOutputStream
import java.io.IOException
import java.io.OutputStreamWriter

class LogCSVWriter @Throws(FileNotFoundException::class, RuntimeException::class) constructor(
    filename: String,
    dirname: String,
    context: Context
) {

    private val TAG = LogCSVWriter::class.java.name
    private val HEADER_CSV = "This is a logfile generated by pires.obd.reader"
    private val NAMES_COLUMNS_ONLY_READINGS = arrayOf(
        "BAROMETRIC_PRESSURE", "ENGINE_COOLANT_TEMP", "FUEL_LEVEL", "ENGINE_LOAD", "AMBIENT_AIR_TEMP",
        "ENGINE_RPM", "INTAKE_MANIFOLD_PRESSURE", "MAF", "Term Fuel Trim Bank 1",
        "FUEL_ECONOMY", "Long Term Fuel Trim Bank 2", "FUEL_TYPE", "AIR_INTAKE_TEMP",
        "FUEL_PRESSURE", "SPEED", "Short Term Fuel Trim Bank 2",
        "Short Term Fuel Trim Bank 1", "ENGINE_RUNTIME", "THROTTLE_POS", "DTC_NUMBER",
        "TROUBLE_CODES", "TIMING_ADVANCE", "EQUIV_RATIO"
    )

    private var isFirstLine = true
    private val buf: BufferedWriter
    private val columns: Array<String>

    init {
        try {
            val sdCard = Environment.getExternalStorageDirectory()
            val dir = File(sdCard.absolutePath + File.separator + dirname)
            if (!dir.exists()) dir.mkdirs()
            Log.d(TAG, "Path is ${sdCard.absolutePath}${File.separator}$dirname")

            val file = File(dir, filename)
            val fos = FileOutputStream(file)
            val osw = OutputStreamWriter(fos)
            buf = BufferedWriter(osw)
            isFirstLine = true

            var csvHeader = ""
            val readings = mutableListOf<String>()

            if (file.length() == 0L) {
                for (command in ObdConfig.getCommands()) {
                    if (PreferencesHelper.getCommandEnabledSync(context, command.getName())) {
                        val cmdId = getCmdID(command.getName())
                        csvHeader = if (csvHeader.isEmpty()) cmdId else "$csvHeader;$cmdId"
                        readings.add(cmdId)
                    }
                }
            }

            columns = readings.toTypedArray()
            Log.d(TAG, "Constructed the LogCSVWriter")
        } catch (e: Exception) {
            e.printStackTrace()
            throw RuntimeException("LogCSVWriter constructor failed", e)
        }
    }

    private fun getCmdID(cmdName: String): String {
        for (c in AvailableCommandNames.values()) {
            if (c.getValue().equals(cmdName)) return c.toString()
        }
        return ""
    }

    @Synchronized
    fun closeLogCSVWriter() {
        try {
            buf.flush()
            buf.close()
            Log.d(TAG, "Flushed and closed")
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }

    @Synchronized
    fun writeLineCSV(reading: ObdReading) {
        val crl = if (isFirstLine) {
            isFirstLine = false
            var line = "TIME;LATITUDE;LONGITUDE;ALTITUDE;VEHICLE_ID;"
            for (ccln in columns) {
                line += "$ccln;"
            }
            line.substring(0, line.length - 1)
        } else {
            var line = "${reading.timestamp};${reading.latitude};${reading.longitude};${reading.altitude};${reading.vin};"
            val readMap = reading.readings
            for (ccln in columns) {
                line += "${readMap[ccln]};"
            }
            line.substring(0, line.length - 1)
        }

        addLine(crl)
    }

    private fun addLine(line: String?) {
        if (line != null) {
            try {
                buf.write(line, 0, line.length)
                buf.newLine()
                Log.d(TAG, "LogCSVWriter: Wrote$line")
            } catch (e: IOException) {
                e.printStackTrace()
            }
        }
    }
}
